---
- name: restart dhcpd
  become: yes
  service: name=dhcpd state=restarted
  delegate_to: "{{ pxeboot_server }}"

- name: restart xinetd
  become: yes
  service: name=xinetd state=restarted

- name: restart httpd
  become: yes
  service: name=httpd state=restarted
