---
- name: restart dhcpd-kickstart
  service: name=dhcpd state=restarted
  when: dhcp_kickstart_handle_dhcpd

- name: restart dhcpd6-kickstart
  service: name=dhcpd6 state=restarted
  when: dhcp_kickstart_handle_dhcpd
